const FETCH_All_PERSONNEL_REQUEST = "FETCH_All_PERSONNEL_REQUEST";
const FETCH_All_PERSONNEL_SUCCESS = "FETCH_All_PERSONNEL_SUCCESS";
const FETCH_All_PERSONNEL_FAILURE = "FETCH_All_PERSONNEL_FAILURE";

export {
  FETCH_All_PERSONNEL_REQUEST,
  FETCH_All_PERSONNEL_SUCCESS,
  FETCH_All_PERSONNEL_FAILURE
};
